using System.Runtime.InteropServices;

namespace DeftSharp.Windows.Input.Native.System;

/// <summary>
/// Contains information about a hardware input event.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct HardwareInput
{
    /// <summary>
    /// The message generated by the input hardware.
    /// </summary>
    public uint uMsg;

    /// <summary>
    /// The low-order word of the lParam parameter for uMsg.
    /// </summary>
    public ushort wParamL;

    /// <summary>
    /// The high-order word of the lParam parameter for uMsg.
    /// </summary>
    public ushort wParamH;
}